name: bereal
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.6
  go_router: ^5.0.3
  country_picker: ^2.0.16
  freezed: ^2.1.1
  freezed_annotation: ^2.1.0
  fluttertoast: ^8.0.9
  flutter_secure_storage: ^6.0.0
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  json_serializable: ^6.4.1
  flutter_native_splash: ^2.2.10+1
  flutter_launcher_icons: ^0.10.0
  cached_network_image: ^3.2.2
  animate_do: ^3.0.2
  dotted_border: ^2.0.0+3
  camera:
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  riverpod_generator: ^1.0.6

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  
flutter_native_splash:
  color: "#000000"
  image: assets/icon/icon.png
  android_12:
    image: assets/icon/icon.png
    icon_background_color: "#000000"
    image_dark: assets/icon/icon.png
    icon_background_color_dark: "#000000"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21